# Generated by Django 5.2.4 on 2025-08-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('author', models.CharField(max_length=300, verbose_name='author')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='published_date')),
                ('is_availabe', models.BooleanField(default=True, verbose_name='available/not available')),
            ],
        ),
    ]
