# Generated by Django 5.2.4 on 2025-08-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='reserver_name',
            field=models.CharField(default='', max_length=300, verbose_name='reserver_name'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='reserver_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='reserver_time'),
        ),
    ]
