# Generated by Django 5.2.4 on 2025-08-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0002_reservations_reserver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='book_reserver',
            field=models.CharField(choices=[('صد سال تنهایی', 'صد سال تنهایی'), ('عقاید یک دلقک', 'عقاید یک دلقک'), ('عنتر و لوتی', 'عنتر و لوتی')], default='صد سال تنهایی', max_length=300),
        ),
    ]
