# Generated by Django 5.2.4 on 2025-08-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0003_reservations_book_reserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='book_reserver',
            field=models.CharField(choices="[('صد سال تنهایی', 'صد سال تنهایی'), ('عقاید یک دلقک', 'عقاید یک دلقک'), ('چشمهایش', 'چشمهایش'), ('مجموعه شعر نیست', 'مجموعه شعر نیست')]", default='', max_length=300),
        ),
    ]
